### PR TITLE
Added backticks around versions.

### PR DESCRIPTION
**Pull request by Utkarsh299-tech**

### CODE REVIEW

**Comment by Vyvy-vi** [comment]
hey @Utkarsh299-tech, can you sync your fork with this repo using `git fetch upstream`?

**Comment by Utkarsh299-tech** [comment]
> hey @Utkarsh299-tech, can you sync your fork with this repo using `git fetch upstream`?
> 
> The CI was broken and has been fixed in the last commit 😅
> Thanks for contributing to TearDrops 🎉

Yes, sure I will do that thanks!

**Comment by Utkarsh299-tech** [comment]
> hey @Utkarsh299-tech, can you sync your fork with this repo using `git fetch upstream`?
> 
> The CI was broken and has been fixed in the last commit 😅
> Thanks for contributing to TearDrops 🎉

Hey @Vyvy-vi, I tried using this command but I'm getting this error. Can you please help me resolve this error?

git

**Comment by Vyvy-vi** [comment]
You'll need to add an `upstream` remote pointing to this repo
And you'll need to reset your `origin` remote to your fork
The following should do this, I think:

```sh
git remote set-url origin https://github.com/Utkarsh299-tech/TearDrops
git remote add upstream https://github.com/Vyvy-vi/TearDrops 
```

After this, you will need to fetch the `upstream` remote using:
```sh
git fetch upstream
git merge upstream/main
git push
```

**Comment by Utkarsh299-tech** [comment]
> You'll need to add an `upstream` remote pointing to this repo
> And you'll need to reset your `origin` remote to your fork
> The following should do this, I think:
> 
> ```shell
> git remote set-url origin https://github.com/Utkarsh299-tech/TearDrops
> git remote add upstream https://github.com/Vyvy-vi/TearDrops 
> ```
> 
> After this, you will need to fetch the `upstream` remote using:
> 
> ```shell
> git fetch upstream
> git merge upstream/main
> git push
> ```

Okay, thank you for this. I did the same as you said. Hoping this PR to be merged!

**Review by Vyvy-vi — APPROVED** [review]
LGTM-!

**Comment by Vyvy-vi** [comment]
Thanks for contributing to TearDrops-! 🎉

**Comment by Vyvy-vi** [comment]
@all-contributors add @Utkarsh299-tech for docs

**Pull request merged**
