### PR TITLE
Update the contributing guide.

### LINKED ISSUE #13: [FEAT]: Update CONTRIBUTING.md
up-for-grabs
preferably something that emphasis no-SPAM and usage of [Commit Guidelines](https://www.conventionalcommits.org/en/v1.0.0/)

### PR DESCRIPTION
**Pull request by anubhavcodes**
Fixes #13 

@Vyvy-vi Please give me feedback if the text in the CONTRIBUTING.md is fitting to this repository or not. 

Thanks to [Red](https://github.com/Cog-Creators/Red-DiscordBot) Bot with the amazing contributing guide.

### CODE REVIEW

**Comment by anubhavcodes** [comment]
I rebased my branch to `upstream/dev` and forced pushed against dev. This should be fine.

**Comment by Vyvy-vi** [comment]
@anubhavcodes I deleted the dev branch a while ago that's why this was auto-closed
Wanna make another pr?

**Comment by anubhavcodes** [comment]
Yes I can do that. Thanks. Please assign me to it.

**Comment by Vyvy-vi** [comment]
@all-contributors add @anubhavcodes code

**Pull request closed without merging**
